# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Unknown Hands'
description:      'Female Scribes in Pre-Modern Europe'
url:              'https://estellegvl.github.io'
baseurl:          '/unknownhands'
copyright:        'Estelle Guéville, 2025'
logo:             '/assets/sticker.png'
default_thumb:    '/assets/sticker.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  unknownhands: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'scribe_item' # the layout for the pages to use
    metadata:
      source: 'unknownhands.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/unknownhands' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      unknownhands:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - call_number
          - label
          - folio

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'Unknown Hands'
        link: '/about/'
      - label: 'Team'
        link: '/team/'
#  - label: 'Exhibits'
#    sub:
#      - label: 'Inline Parallax Image'
#        link: '/exhibits/a/'
#      - label: 'Inline Image References'
#        link: '/exhibits/b/'
  - label: 'Data'
    link: '/data/'
  - label: 'Roadmap'
    link: '/roadmap/'
  - label: 'Bibliography'
    link: '/bibliography/'
  - label: 'Contact'
    link: '/contact/'
#  - label: 'Browse'
#    link: '/collection/'
#  - label: 'Search'
#    link: '/search/'
#  - label: 'Reuse'
#    link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'Credits'
      link: '/credits'
    - label: 'Wiki'
      link: 'https://minicomp.github.io/wiki/wax/'
  logos:
    - img: '/img/sticker.webp'
      fallback: '/img/sticker.png'   # optional, used only when img ends with .webp
      alt: 'Christine of Pizan writing'
  cite: |  
    **Please cite as:**  
    *Unknown Hands. Female Scribes in Pre-1600 Christian Europe*, ed. Estelle Guéville, v.1.1 (2025), URL.
# FIN
